services:
  postgres-organization:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '6742:5432'
    networks:
      - holidayplannernetwork

  organizationservice:
    image: 'swe5076/swe5076:organizationservice_img'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres-organization:5432/mydatabase'
      - 'kafka.server.url=kafka:9092'
    ports:
      - '8082:8082'
    depends_on:
      - postgres-organization
      - kafka
    networks:
      - holidayplannernetwork
