services:
  postgres-event:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '38368:5432'
    networks:
      - holidayplannernetwork

  solr-core5:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./myconfig:/opt/solr/server/solr/configsets/myconfig:ro
    command: solr-precreate event-search /opt/solr/server/solr/configsets/myconfig
    networks:
      - holidayplannernetwork

  eventservice:
    image: 'swe5076/swe5076:eventservice_img'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres-event:5432/mydatabase'
      - 'kafka.server.url=kafka:9092'
      - 'solr.server.url=solr-core5:8983'
    ports:
      - '8081:8081'
    depends_on:
      - postgres-event
      - kafka
    networks:
      - holidayplannernetwork
